import { FuneralHome, Obituary, ActivityLog, AdminMetrics, ChartDataPoint } from './types'

export const mockFuneralHomes: FuneralHome[] = [
  {
    id: '1',
    name: 'Zakład Pogrzebowy Wieczność',
    email: 'biuro@wiecznosc.pl',
    phone: '+48 22 123 45 67',
    address: 'ul. Spokojna 12, 00-001 Warszawa',
    status: 'active',
    qrLimit: 100,
    qrUsed: 67,
    createdAt: '2024-01-15',
    lastLoginAt: '2024-05-25',
  },
  {
    id: '2',
    name: 'Dom Pogrzebowy Ostatnia Droga',
    email: 'kontakt@ostatniadroga.pl',
    phone: '+48 12 987 65 43',
    address: 'ul. Długa 45, 30-001 Kraków',
    status: 'active',
    qrLimit: 50,
    qrUsed: 23,
    createdAt: '2024-02-20',
    lastLoginAt: '2024-05-24',
  },
  {
    id: '3',
    name: 'Usługi Pogrzebowe Cisza',
    email: 'cisza@pogrzeby.pl',
    phone: '+48 61 111 22 33',
    address: 'ul. Polna 8, 60-001 Poznań',
    status: 'inactive',
    qrLimit: 30,
    qrUsed: 30,
    createdAt: '2024-03-10',
    lastLoginAt: '2024-04-10',
  },
  {
    id: '4',
    name: 'Dom Pogrzebowy Pamięć',
    email: 'pamiec@pogrzeby.com.pl',
    phone: '+48 71 555 66 77',
    address: 'ul. Różana 3, 50-001 Wrocław',
    status: 'active',
    qrLimit: 200,
    qrUsed: 142,
    createdAt: '2023-11-05',
    lastLoginAt: '2024-05-26',
  },
  {
    id: '5',
    name: 'Zakład Pogrzebowy Spokój',
    email: 'biuro@spokojpogrzeby.pl',
    phone: '+48 42 333 44 55',
    address: 'ul. Lipowa 21, 90-001 Łódź',
    status: 'suspended',
    qrLimit: 75,
    qrUsed: 0,
    createdAt: '2024-04-01',
    lastLoginAt: '2024-04-01',
  },
]

export const mockObituaries: Obituary[] = [
  {
    id: '1',
    funeralHomeId: '1',
    funeralHomeName: 'Zakład Pogrzebowy Wieczność',
    firstName: 'Jan',
    lastName: 'Kowalski',
    birthDate: '1945-03-15',
    deathDate: '2024-05-20',
    obituaryText:
      'Z głębokim żalem zawiadamiamy o odejściu naszego ukochanego Ojca, Dziadka i Przyjaciela. Jan Kowalski przez całe życie służył innym z pokorą i serdecznością. Zostawił w naszych sercach ślad, który nigdy nie zniknie.',
    ceremonyInfo: 'Msza święta żałobna odbędzie się 25 maja 2024 r. o godz. 11:00',
    location: 'Kościół pw. Wniebowzięcia NMP, ul. Kościelna 1, Warszawa',
    status: 'published',
    qrCode: 'QR-2024-001',
    publicUrl: '/obituary/jan-kowalski-2024',
    views: 245,
    createdAt: '2024-05-21',
    publishedAt: '2024-05-21',
  },
  {
    id: '2',
    funeralHomeId: '1',
    funeralHomeName: 'Zakład Pogrzebowy Wieczność',
    firstName: 'Maria',
    lastName: 'Nowak',
    birthDate: '1938-07-22',
    deathDate: '2024-05-18',
    obituaryText:
      'Pożegnaliśmy naszą drogą Mamę, Babcię, ukochaną żonę. Maria Nowak była filarem naszej rodziny przez ponad 80 lat. Jej ciepło i mądrość będą dla nas zawsze inspiracją.',
    ceremonyInfo: 'Uroczystości pogrzebowe odbędą się 23 maja 2024 r. o godz. 10:00',
    location: 'Cmentarz Bródnowski, Warszawa',
    status: 'published',
    qrCode: 'QR-2024-002',
    publicUrl: '/obituary/maria-nowak-2024',
    views: 189,
    createdAt: '2024-05-19',
    publishedAt: '2024-05-19',
  },
  {
    id: '3',
    funeralHomeId: '2',
    funeralHomeName: 'Dom Pogrzebowy Ostatnia Droga',
    firstName: 'Stanisław',
    lastName: 'Wiśniewski',
    birthDate: '1952-11-08',
    deathDate: '2024-05-22',
    obituaryText:
      'Z wielkim bólem serca żegnamy naszego kochanego Tatę. Stanisław Wiśniewski przez całe życie pracował z pasją i poświęceniem. Będzie nam bardzo brakować jego poczucia humoru.',
    ceremonyInfo: 'Ceremonię pożegnalną zaplanowano na 27 maja 2024 r. o godz. 12:00',
    location: 'Kaplica Cmentarna, ul. Raszyńska 26, Kraków',
    status: 'draft',
    views: 0,
    createdAt: '2024-05-23',
  },
  {
    id: '4',
    funeralHomeId: '4',
    funeralHomeName: 'Dom Pogrzebowy Pamięć',
    firstName: 'Zofia',
    lastName: 'Wróbel',
    birthDate: '1930-01-30',
    deathDate: '2024-05-15',
    obituaryText:
      'Odeszła od nas nasza Droga Babcia, Prababcia, matka trojga dzieci. Zofia Wróbel przeżyła 94 piękne lata, w tym wiele trudnych, dając nam zawsze przykład siły i wiary.',
    ceremonyInfo: 'Msza pogrzebowa 19 maja 2024 r. o godz. 10:00',
    location: 'Bazylika pw. Najświętszego Serca Jezusowego, Wrocław',
    status: 'archived',
    qrCode: 'QR-2024-003',
    publicUrl: '/obituary/zofia-wrobel-2024',
    views: 312,
    createdAt: '2024-05-15',
    publishedAt: '2024-05-16',
  },
  {
    id: '5',
    funeralHomeId: '2',
    funeralHomeName: 'Dom Pogrzebowy Ostatnia Droga',
    firstName: 'Tadeusz',
    lastName: 'Mazur',
    birthDate: '1960-06-14',
    deathDate: '2024-05-25',
    obituaryText:
      'Z niezmiernym żalem informujemy o nagłym odejściu Tadeusza Mazura. Był wspaniałym mężem, ojcem i przyjacielem. Jego energia i zaangażowanie w życie rodziny i społeczności pozostaną w naszej pamięci.',
    ceremonyInfo: 'Pogrzeb odbędzie się 30 maja 2024 r. o godz. 13:00',
    location: 'Cmentarz Rakowicki, Kraków',
    status: 'published',
    qrCode: 'QR-2024-004',
    publicUrl: '/obituary/tadeusz-mazur-2024',
    views: 87,
    createdAt: '2024-05-26',
    publishedAt: '2024-05-26',
  },
  {
    id: '6',
    funeralHomeId: '2',
    funeralHomeName: 'Dom Pogrzebowy Ostatnia Droga',
    firstName: 'Anna',
    lastName: 'Kowalczyk',
    birthDate: '1949-09-03',
    deathDate: '2024-05-10',
    obituaryText:
      'Żegnamy Annę Kowalczyk, nauczycielkę z powołania, która przez 35 lat kształtowała umysły i serca młodych ludzi.',
    ceremonyInfo: 'Uroczystość pogrzebowa odbyła się 15 maja 2024 r.',
    location: 'Kościół pw. św. Anny, Kraków',
    status: 'archived',
    qrCode: 'QR-2024-005',
    publicUrl: '/obituary/anna-kowalczyk-2024',
    views: 421,
    createdAt: '2024-05-11',
    publishedAt: '2024-05-11',
  },
]

export const mockActivityLog: ActivityLog[] = [
  {
    id: '1',
    type: 'obituary_published',
    description: 'Opublikowano nekrolog: Tadeusz Mazur',
    funeralHomeName: 'Dom Pogrzebowy Ostatnia Droga',
    timestamp: '2024-05-26T14:32:00',
  },
  {
    id: '2',
    type: 'obituary_created',
    description: 'Utworzono nekrolog: Stanisław Wiśniewski',
    funeralHomeName: 'Dom Pogrzebowy Ostatnia Droga',
    timestamp: '2024-05-23T09:15:00',
  },
  {
    id: '3',
    type: 'obituary_published',
    description: 'Opublikowano nekrolog: Jan Kowalski',
    funeralHomeName: 'Zakład Pogrzebowy Wieczność',
    timestamp: '2024-05-21T11:45:00',
  },
  {
    id: '4',
    type: 'qr_generated',
    description: 'Wygenerowano kod QR dla: Maria Nowak',
    funeralHomeName: 'Zakład Pogrzebowy Wieczność',
    timestamp: '2024-05-19T15:22:00',
  },
  {
    id: '5',
    type: 'obituary_published',
    description: 'Opublikowano nekrolog: Zofia Wróbel',
    funeralHomeName: 'Dom Pogrzebowy Pamięć',
    timestamp: '2024-05-16T10:05:00',
  },
  {
    id: '6',
    type: 'client_created',
    description: 'Zarejestrowano klienta: Zakład Pogrzebowy Spokój',
    funeralHomeName: 'System',
    timestamp: '2024-04-01T08:00:00',
  },
]

export const mockAdminMetrics: AdminMetrics = {
  totalFuneralHomes: 5,
  totalObituaries: 47,
  totalQrUsed: 262,
  activeClients: 3,
}

export const mockChartData: ChartDataPoint[] = [
  { month: 'Sty', obituaries: 8, qrUsed: 8 },
  { month: 'Lut', obituaries: 12, qrUsed: 12 },
  { month: 'Mar', obituaries: 15, qrUsed: 14 },
  { month: 'Kwi', obituaries: 19, qrUsed: 18 },
  { month: 'Maj', obituaries: 23, qrUsed: 22 },
]

export const mockFuneralHomeMetrics = {
  totalObituaries: 6,
  remainingQr: 27,
  publishedObituaries: 4,
  draftObituaries: 1,
}

export const funeralHomeObituaries = mockObituaries.filter(
  (o) => o.funeralHomeId === '2'
)
